### ISSUE TITLE
BFI Integration

### ISSUE THREAD

**Issue by sphyx42** [zzp8202/Double_GEAR_ratio_Z#3]
Hello There!!

I'm working on integrating your mod into my build and noticed that the front top pulley adapter is sized for the original Front Idler setup with 2x M5 bolts. Since I'm running the BFI mod, the Pulley Adapter doesn't work out.

I was unable to add a pull request for some reason, probably because I'm newer at doing that stuff in Github; but I adapted the adapter to fit the BFI: I shortened it by 3mm and replaced one M5 bolt hole for an M3 bolt hole and ensured everything lined up on the BFI.

I can share both the CAD and STL with you, just not sure how at the moment.

Thanks!!

**Comment by zzp8202** [comment]
I saw your Pull requests, please see the comment in pull requests.
